### ISSUE TITLE
Responsive CSS

### ISSUE THREAD

**Issue by YuriGor** [leongersen/noUiSlider#1034]
Hi, very cool sliders, thank you very much!
I noticed that default CSS is designed for the specific size of the container element, so it looks bad in the arbitrary containers.
But it's pretty easy to make sliders responsive by minor changes in CSS only.
Here is how it looks like currently and after applying 'responsive' CSS:
![image](https://user-images.githubusercontent.com/6861317/68995498-fa8acc80-088e-11ea-9c26-ef67ff819e61.png)
Here is a CSS override:
_(I made it optional, to be applied only if container has 'responsive' class)_
```css
.responsive.noUi-horizontal .noUi-handle {
  height: 100%;
  top: -6px;
}

.responsive.noUi-horizontal .noUi-origin {
  height: calc(100% + 12px);
}
.responsive.noUi-horizontal .noUi-handle:before,
.responsive.noUi-horizontal  .noUi-handle:after {
  height: 50%;
  top: 25%;
}


.responsive.noUi-vertical .noUi-handle {
  width: 100%;
  left: -6px;
}

.responsive.noUi-vertical .noUi-origin {
  width: calc(100% + 12px);
}
.responsive.noUi-vertical .noUi-handle:before,
.responsive.noUi-vertical  .noUi-handle:after {
  width: 50%;
  left: 25%;
}
```
[Here you can play with it](https://codepen.io/yurigor/pen/vYYQVdZ)

Let me know if you are interested in PR for making this built-in.
