### ISSUE TITLE
Run without css transform?

### ISSUE THREAD

**Issue by AAverin** [leongersen/noUiSlider#1134]
I am running my code in an environment that doesn't support css transitions and animations (sic!) - https://www.adobe.io/photoshop/uxp/uxp/known-issues/
Is it technically possible to run noUiSlider without them?

**Comment by leongersen** [comment]
Yes, you can set the `animate` option to `false` to disable animations, and disable the transition in CSS.

https://refreshless.com/nouislider/slider-options/#section-animate

```CSS
.noUi-state-tap .noUi-connect,
.noUi-state-tap .noUi-origin {
    -webkit-transition: none;
    transition: none;
}
```
