### ISSUE TITLE
Larger clickable area when slider is small

### ISSUE THREAD

**Issue by AAverin** [leongersen/noUiSlider#1172]
When slider itself is very small with `tap` behavior set, it would be great to somehow set tappable area larger so that user could click around the slider and pips would still move. See image for reference.

![image](https://user-images.githubusercontent.com/1481332/141614798-0ddc4ff6-f7ab-4914-a262-82ea08e56f46.png)

**Comment by leongersen** [comment]
You can do this by making `.noUi-base` larger. For the default styling, that'd look like this:

```CSS
.noUi-base {
    height: 200%;
}
.noUi-connects {
    height: 50%;
}
```

You can center this tap area by pulling it up, and pushing the connect elements and handles down:

```CSS
.noUi-base {
    top: -8px;
}
.noUi-connects
.noUi-origin {
    top: 8px
}
```
