### ISSUE TITLE
Checkbox position not right in RTL

### ISSUE THREAD

**Issue by Stevemoretz** [leongersen/noUiSlider#1236]
LTR:

<img width="346" alt="Screen Shot 1401-10-21 at 18 09 35" src="https://user-images.githubusercontent.com/27680142/211834617-46351cbf-d308-47cc-9d83-463a407e64b0.png">

RTL:

<img width="344" alt="Screen Shot 1401-10-21 at 18 09 24" src="https://user-images.githubusercontent.com/27680142/211834695-6b325db8-a422-42f8-9a9e-cc0904bfa722.png">

The fix is:

```css
        [dir="rtl"] .facetwp-checkbox{
            padding-right: 20px;
            padding-left: unset;
            background-position: right;
        }
```

Which makes the RTL to be :

<img width="343" alt="Screen Shot 1401-10-21 at 18 09 30" src="https://user-images.githubusercontent.com/27680142/211834840-ddedacee-c289-4e14-9d77-03aabae2973e.png">
