### ISSUE TITLE
misaligned sliders

### ISSUE THREAD

**Issue by Lunarequest** [leongersen/noUiSlider#1240]
I update my nouislider install and well the sliders are just all over the place not aligned. Any help would be nice

![image](https://user-images.githubusercontent.com/30698906/217134796-d8352b0d-ee63-44af-b828-a3dc494d2849.png)

**Comment by leongersen** [comment]
Make sure to update the CSS as well.

**Comment by Lunarequest** [comment]
I have updated the css as well.

**Comment by leongersen** [comment]
You likely have a conflict in your custom CSS, see:
https://github.com/leongersen/noUiSlider/blob/master/CHANGELOG.MD#1550-2021-09-01

**Comment by Lunarequest** [comment]
I inherited this css and don't really understand it. Would you be able to point out where it conflicts 
```css
#darkConfigurator {
    position: absolute;
    top: 28px;
    right: 42px;
    height: 550px;
    width: 200px;
    z-index: 999;
    background: rgb(45, 45, 45);
    border: 1px solid #666666;
    color: white;
    display: flex;
    flex-direction: column;
    justify-content: flex-start;
    align-items: flex-start;
    padding: 16px 24px;
    box-sizing: border-box;
    border-radius: 4px;
    -webkit-box-shadow: 2px 2px 5px 0px rgba(0, 0, 0, 0.6);
    box-shadow: 2px 2px 5px 0px rgba(0, 0, 0, 0.6);
    visibility: hidden;
}

#slides label {
    font-size: 14px;
}

#slides {
    margin-top: 12px;
    width: 100%;
    height: 200px;
}

#darkConfigurator h3 {
    margin-top: 0px;
    margin-bottom: 0px;
}

#slides > div {
    margin-top: 4px;
    margin-bottom: 34px;
}

#darkConfigurator div .noUi-handle {
    width: 25px;
    height: 25px;
    border-radius: 25px;
    left: 2px;
    right: 2px;
    top: -4px;
}

#darkConfigurator div .noUi-active {
    box-shadow: none;
    outline: none;
}

#darkConfigurator div .noUi-active:focus {
    outline: none;
    box-shadow: none;
}

#darkConfigurator *:focus {
    outline: none;
    box-shadow: none;
}

#darkConfigurator *:active {
    outline: none;
}

#darkConfigurator .noUi-tooltip {
    bottom: -108%;
    font-size: 13px;
    padding: 2px;
    padding-left: 3px;
    padding-right: 3px;
    font-family: Helvetica, sans-serif;
    background-color: black;
    border: 2px solid rgb(24, 24, 24);
    color: #dddddd;
}

#darkConfigurator .noUi-tooltip::before {
    content: '';
    position: absolute;
    display: block;
    width: 0px;
    left: 50%;
    top: 10px;
    border: 7px solid transparent;
    border-top: 0;
    border-bottom: 12px solid black;
    transform: translate(-50%, calc(-100% - 5px));
}

#darkConfigurator .noUi-target {
    border: none;
    border-radius: 15px;
    background: transparent;
}

#darkConfigurator .noUi-connects {
    background-color: rgb(45, 45, 45);
    box-shadow: rgba(7, 7, 6, 0.9) 0px 1px 3px inset;
    border-radius: 15px;
}

#darkConfigurator .noUi-connect {
    background: rgb(144, 165, 130);
    box-shadow: rgba(7, 7, 6, 0.3) 0px 1px 3px inset;
}

#darkConfigurator div .noUi-handle {
    background-color: rgb(34, 33, 32);
    border-top-color: rgb(72, 70, 66);
    border-right-color: rgb(72, 70, 66);
    border-bottom-color: rgb(72, 70, 66);
    border-left-color: rgb(72, 70, 66);
    background-image: linear-gradient(rgba(34, 33, 32, 0), rgba(7, 7, 6, 0.1));
    box-shadow: rgba(7, 7, 6, 0.3) 0px 0px 8px;
}

#darkConfigurator div .noUi-handle:before {
    left: 0;
    background: none;
}

#darkConfigurator div .noUi-handle:after {
    left: 0;
    background: none;
}

#darkConfigurator select {
    margin-top: 8px;
    width: 100%;
    height: 25px;
    font-size: 14px;
    color: rgb(144, 165, 130);
    background-color: rgb(45, 45, 45);
}

#darkConfigurator .noUi-horizontal {
    height: 14px;
}
 ```
