### ISSUE TITLE
Question: How to make thumbs not overlapping by each other but keep full range functionality

### ISSUE THREAD

**Issue by kanopa** [leongersen/noUiSlider#1259]
I have something similar to this example https://refreshless.com/nouislider/examples/#section-values, but i want what thumbs not overlaps. If do this with margin i loose some of values, but i need keep all of them. How i can do this?
Thanks for any help

**Comment by leongersen** [comment]
You can do this by offsetting the `right` styling on the handles.

```CSS
#slider-no-overlap .noUi-handle-lower {
    right: 0;
}
#slider-no-overlap .noUi-handle-upper {
    right: -34px;
}
```

I've added this example to the documentation:
https://refreshless.com/nouislider/examples/#section-styling
