### ISSUE TITLE
question about css

### ISSUE THREAD

**Issue by felixjet** [leongersen/noUiSlider#163]
Hi Leon,

question about what you say on docs with:

"To position your handles on the center of its relative position, it should have a negative offset of half the handle width. See the default theme for reference."

for example:

``` CSS
.noUi-vertical .noUi-handle {
    width: 28px;
    height: 34px;
    left: -6px;
    top: -17px;
}
```

34 height, 17 top. thats fine. but what about the width? shouldnt left be -14px instead of 6? where the 6 come from?

thx
