### ISSUE TITLE
How to change position noUi-base and noUI-pips?

### ISSUE THREAD

**Issue by sieulog** [leongersen/noUiSlider#563]
Hello everybody!

I want change position of noUI base and noUI-pips. Currently, noUI-base above noUI-pips. I want change noUI-pips above noUI-base. Please help me!

**Comment by leongersen** [comment]
You can do this in CSS:

```CSS
.noUi-pips-horizontal { top: -70px }
.your-slider-parent-class { padding-top: 70px; }
```
