### ISSUE TITLE
Hide a knob [feature]

### ISSUE THREAD

**Issue by Pipozor** [leongersen/noUiSlider#576]
It would be nice to have a new feature to hide both (or desired) knob BUT NOT THE TOOLTIP (like for the disabled functions) :

    // To disable
    slider.setAttribute('hideHandle', true);
	
    // To re-enable
	slider.removeAttribute('hideHandle');
	
	// To disable one handle
	var origins = slider.getElementsByClassName('noUi-origin');
	origins[0].setAttribute('hideHandle', true);

Why ?
Because sometimes it's nice to use the slider functionality (animation, tooltips...) without showing the knob. Typically I disabled the knob but I want it becomes hidden too.

Alternatively I'm "patching" css to have the tooltip above the disabled knob. It's not very elegant but it works in my case :

    slider.setAttribute("disabled", true);
    $(this).find(".noUi-handle-upper .noUi-tooltip").css("z-index", "1000");    // place over to hide the knob
    $(this).find(".noUi-tooltip").css("top", -4);   // recenter on slider

**Comment by leongersen** [comment]
It can be done in CSS:

```CSS
[disabled] .noUi-handle { background: none; border: none; }
[disabled] .noUi-handle:before,
[disabled] .noUi-handle:after { content: none; }
```
