### ISSUE TITLE
Any way to remove the blue border on :focus in Chrome?

### ISSUE THREAD

**Issue by EastSideCode** [leongersen/noUiSlider#811]
CSS can't seem to remove this border. Any solution?

**Comment by QuentinRoy** [comment]
`outline: none` does not work ? For example:
```css
.noUi-handle {
  outline: none;
}
.noUi-handle:focus {
  outline: none;
}
```
Note that this blue border is here for accessibility issue. It might be a bad idea to remove it.
